# Generated by Django 3.1.3 on 2020-11-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=120, unique=True, verbose_name='Город')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.CharField(max_length=60, unique=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('map_code', models.TextField(blank=True, verbose_name='Код для карты')),
            ],
        ),
    ]
