# Generated by Django 3.1.3 on 2020-12-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_flag',
            field=models.BinaryField(max_length=2, verbose_name='Наличие на главной', blank=True),
        ),
    ]
