# Generated by Django 3.1.3 on 2020-12-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_product_main_flag'),
    ]

    
