# Generated by Django 3.1.3 on 2020-12-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20201206_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategories',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активно'),
        ),
    ]
