# Generated by Django 3.1.3 on 2021-01-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_product_is_active'),
    ]

    
