# Generated by Django 3.1.3 on 2021-01-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210113_1640'),
    ]

   
