# Generated by Django 3.1.3 on 2021-01-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20210113_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активно'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_flag',
            field=models.BooleanField(default=False, verbose_name='Наличие на главной'),
        ),
    ]
